### ISSUE TITLE
Broken Link https://www.open.ru/

### ISSUE THREAD

**Issue by bcye** [bcye/Hello-Goodbye#112]
### Link
[Visit Broken Site](https://www.open.ru/)

**Comment by Archit-Kohli** [comment]
Where is this broken link situated? I would like to work on this issue

**Comment by bcye** [comment]
@Archit-Kohli  Click Visit Broken Site and see if you can find a chatbot that isnt blocked by the extension. If there is none,.we can close this issue, otherwise you will need to find the script source for thst chatbot and add it to the blocklists

**Comment by Archit-Kohli** [comment]
There is no chat bot on this website

**Comment by bcye** [comment]
Ok
