### ISSUE TITLE
Block Tidio’s widget (tidiochat.com)

### ISSUE THREAD

**Issue by roryokane** [bcye/Hello-Goodbye#16]
I have never personally seen a site that uses that the [Tidio](https://www.tidiochat.com/en/) chat widget, but newscracker on Hacker News wrote [a comment](https://news.ycombinator.com/item?id=19413061) suggesting that it be added to the filter list. They added the following line to the filter list:

~~~
||tidiochat.com/
~~~

Ideally, this URL could be refined into a more specific URL that blocks only their chat widget, not the whole site.

**Comment by bcye** [comment]
I will look into this.

**Comment by bcye** [comment]
solved.
