### ISSUE TITLE
Add a license to the root of the repo

### ISSUE THREAD

**Issue by roryokane** [bcye/Hello-Goodbye#18]
It would be nice if you added a license to the root of your repository so that it would clearly be open source. I see that there is a license file at [`docs/LICENSE`](https://github.com/bcye/Hello-Goodbye/blob/master/docs/LICENSE), but it is unclear whether this applies to the extensions and filter list or just to the contents of the `docs` folder. Another reason to add a license to the root is that GitHub will show the license in the top right of the [repo’s main page](https://github.com/bcye/Hello-Goodbye).

You probably already know how to add a license, but here is a link to [GitHub Help – Licensing a repository](https://help.github.com/en/articles/licensing-a-repository) just in case.

**Comment by bcye** [comment]
Done.
