### ISSUE TITLE
Extension New Permission

### ISSUE THREAD

**Issue by skiman6010** [bcye/Hello-Goodbye#27]
Seems that Hello, Goodbye! was updated recently and needs the permission to "Read your browsing history". 

Why is this needed now and not before?

![Screenshot 2019-04-14 at 16 31 08](https://user-images.githubusercontent.com/8137212/56098835-e2a33280-5ed2-11e9-80c0-e8d1c02afd39.png)

**Comment by bcye** [comment]
With the last update I introduced a feature which sets a "HELP" badge when visiting a site where a chat widget was blocked. Try it out on intercom.com or getmakerlog.com or whatever.

To do this, I needed to be able to use the tabs api, I think this could be because of that.

**Comment by skiman6010** [comment]
Well that's too bad then. 

Thanks for the information though.

**Comment by bcye** [comment]
I think though that I could cut down some of the permissions. Do you have experience with this? I think some of them might be unnecessary

**Comment by skiman6010** [comment]
I do not have much experience with this, but I'm willing to help in any way that I can.
