### ISSUE TITLE
Wanting to join this project? Look here.

### ISSUE THREAD

**Issue by bcye** [bcye/Hello-Goodbye#28]
Hello,

I have been looking for some way to have more people involved in this, at the end this is an open source project with 130 ⭐️, 14 forks and 5 watchers.

My idea (with inspiration from helpful friends on [Twitter](https://twitter.com/bcye_tw/status/1125973647699505152)) is to start things of with creating a group on Slack or Discord where we can discuss product development, growth, design, and more.
I personally dislike IRC, because it feels clunky, but if I'm the only one I will look into it.

**Please cast your vote in the discussions, if you would prefer using Slack or Discord. All further discussions can happen then in the group of collaborators.**

I hope we can get together at least 4 people, 6 would be optimal.

Have an awesome day,
bcye!

**Comment by bcye** [comment]
In case you are wondering, I would not want to use Telegram, since it does not have the option for multiple channels.

**Comment by FabioRosado** [comment]
I got to say that I am not very keen on Discord, for some reason I find it hard to keep track of the chats on all the different channels. I'd vote for Slack since you can create threads from a topic and it makes it easier for people to follow up discussions

**Comment by bcye** [comment]
@FabioRosado @gjain574 Ok sounds good to me, I personally prefer slack as well.

I'll set up a workspace.

**Comment by bcye** [comment]
**UPDATE: I SET UP A WORKSPACE**


https://join.slack.com/t/hello-goodbye-group/shared_invite/enQtNjIzODEyODEwMjQxLTEzY2VkNTY4OTBlNDkwMGU0ZGRiM2Y1OTA5NDcxNDhiMmQ0MTI4ZGQwNjhhYjVkNzRjNGNiNGJjMTEwZjU1ZjM

See you there

Tagging @gjain574 @FabioRosado

**Comment by WebMaye** [comment]
I'm in for slack

**Comment by bcye** [comment]
Awesome! Can you join the slack?

**Comment by bcye** [comment]
Just noticed I hat a typo in the invite URL.


@WebMaye @FabioRosado please join https://join.slack.com/t/hellogoodbyeextension/shared_invite/enQtNjMwMTY2OTQ5NzYwLWUxYmFkOTU1ZjFhNTNlYjY1YjA3YTJhY2U1YjY5Mzk5NmQ1OWZlZmYwNDNkNWQ4ZGUxNjEwYzM3YjQ1MzA2YWU
