### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by bcye** [bcye/Hello-Goodbye#31]
My idea for a new logo was to make something similar to ABP (Adblock Plus)

E.g. a red stop sign, but instead having a "stop" hand in the middle, we could have a chat icon in the middle.

What do you think?

**Comment by munadikieh** [comment]
@bcye Hi, my name is Munadi Kiehl. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem.

**Comment by bcye** [comment]
@mundikieh apologies, I didn’t close the issue.

Another designer already made a new logo. 

Thank you for your interest :)
