### ISSUE TITLE
Does not work on Windows 10 Edge (Chromium)

### ISSUE THREAD

**Issue by bcye** [bcye/Hello-Goodbye#38]
Someone reported to me via email, that the extension does not work on Windows 10 Edge (Chromium).

I installed it on the Chromium Edge for Mac, but there it is working perfectly fine.
Would someone with Windows be able to install the extension on Edge and debug what is wrong?

**Comment by fredster33** [comment]
Works for me personally.

**Comment by bcye** [comment]
OK, thanks for checking, I will close this issue then until someone raises this error again.
