### ISSUE TITLE
AdBlock filter list

### ISSUE THREAD

**Issue by tbodt** [bcye/Hello-Goodbye#4]
I use Safari, so both the published extensions wouldn't work. But I do have uBlock Origin, which can parse adblock filter lists. So if this was published in that form, I could use it pretty easily, without having to install anything.

**Comment by bcye** [comment]
1. I have looked into Safari, but the development is quite complicated (very error prone). There's still the Xcode Stuff in this repository, so if you'd like you could solve the Safari version and make a PR

2. How do I create a filter list?

**Comment by tbodt** [comment]
I believe you create .txt with the syntax described here https://adblockplus.org/filter-cheatsheet and make it available on some URL (github raw links work fine). The filter could then be imported into most existing adblock extensions, including uBlock Origin for Safari.

**Comment by bcye** [comment]
thanks for the information. I'll look into it.

**Comment by bcye** [comment]
added in commit https://github.com/bcye/Hello-Goodbye/commit/f2ed6da30d90f337e3711754d172d1f7162748a5

**Comment by dartraiden** [comment]
Would you please add `[Adblock Plus 2.0]` as the first line of the header?

This will not break compatibility with uBlock but will add compatibility with Adblock Plus.
