### ISSUE TITLE
Why do you often use so specific filters?

### ISSUE THREAD

**Issue by 07416** [bcye/Hello-Goodbye#48]
`||www.couchbase.com/webfiles/1552355627964/js/contact-popup-form.js`

Why not replacing for instance this one with `||www.couchbase.com/webfiles/*/js/contact-popup-form.js` or `||couchbase.com/webfiles/*/js/contact-popup-form.js` (`www` removed)?

**Comment by bcye** [comment]
I did this more with recent additions, but thanks for mentioning it will change it :)
