### ISSUE TITLE
Change icon to indicate presence of widget

### ISSUE THREAD

**Issue by mrvdot** [bcye/Hello-Goodbye#7]
One thing that would be nice is if the extension icon changed to show that a chat widget had been blocked, so if I did need to talk to support for some reason, I could easily tell that a widget was available

**Comment by bcye** [comment]
That sounds like a good idea. I have a heavy load this week but I'll try to look into it next week.

If anyone wants to tackle this, feel free to fork and PR

**Comment by bcye** [comment]
working on this now 👍

**Comment by bcye** [comment]
Solved in latest commit
